spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3366/store
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB    #手动修改SpringMVC默认上传文件的大小
      max-request-size: 15MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis-config.xml
user:
  address:
    max-count: 20

